export interface Problem {
  id: string;
  name: string;
  icon: string;
  category: 'coral' | 'fish' | 'water' | 'algae' | 'equipment';
  urgency: 'critical' | 'high' | 'medium' | 'low';
  symptoms: string[];
  causes: string[];
  solutions: string[];
  prevention: string[];
  relatedParams?: string[];
}

export const PROBLEMS: Problem[] = [
  // ── Critical ──────────────────────────────────────────────
  {
    id: 'ammonia-spike',
    name: 'Ammonia Spike',
    icon: 'warning',
    category: 'water',
    urgency: 'critical',
    symptoms: [
      'Fish gasping at the surface',
      'Red or inflamed gills',
      'Lethargy and loss of appetite',
      'Fish sitting at the bottom, not swimming',
    ],
    causes: [
      'Dead animal or uneaten food decomposing',
      'Overstocking or overfeeding',
      'Filter failure or crash in biological filtration',
      'New tank syndrome (uncycled tank)',
    ],
    solutions: [
      'Perform an immediate 50% water change with temperature-matched saltwater',
      'Stop all feeding for 24-48 hours',
      'Inspect the tank for dead animals or rotting food and remove immediately',
      'Add activated carbon to the filter to absorb toxins',
      'Dose a quality ammonia detoxifier (e.g., Seachem Prime)',
      'Test ammonia every 6 hours until it reads 0 ppm',
      'Add bottled beneficial bacteria (e.g., Fritz TurboStart)',
    ],
    prevention: [
      'Never overfeed — feed only what fish consume in 2 minutes',
      'Maintain a consistent cleaning schedule',
      'Quarantine new livestock before adding to display',
      'Keep a backup power source for filters',
    ],
    relatedParams: ['ammonia', 'nitrite', 'nitrate', 'pH'],
  },
  {
    id: 'coral-bleaching',
    name: 'Coral Bleaching',
    icon: 'brightness_alert',
    category: 'coral',
    urgency: 'critical',
    symptoms: [
      'White or pale tissue appearing on corals',
      'Polyp retraction and refusal to open',
      'Tissue becoming translucent, skeleton visible',
      'Loss of vibrant coloration over days',
    ],
    causes: [
      'Temperature too high (above 82°F / 28°C)',
      'Sudden changes in lighting intensity or spectrum',
      'Prolonged parameter instability (Alk, Ca, Mg)',
      'Chemical contamination (copper, heavy metals)',
    ],
    solutions: [
      'Reduce light intensity by 30% immediately',
      'Check and stabilize temperature to 77-79°F (25-26°C)',
      'Test and stabilize all major parameters (Alk, Ca, Mg, salinity)',
      'Feed amino acids and coral food to aid recovery',
      'Increase water flow around affected corals',
      'Avoid moving or fragging stressed corals',
      'If caused by new lights, acclimate slowly over 2 weeks',
    ],
    prevention: [
      'Use a temperature controller with heater and chiller/fan',
      'Acclimate new corals to your light slowly (ramp over 2 weeks)',
      'Keep parameters stable — consistency matters more than perfection',
      'Test weekly and dose daily if needed',
    ],
    relatedParams: ['temperature', 'alkalinity', 'calcium', 'magnesium', 'salinity'],
  },
  {
    id: 'fish-ich',
    name: 'Fish Disease (Ich / White Spot)',
    icon: 'coronavirus',
    category: 'fish',
    urgency: 'critical',
    symptoms: [
      'White dots (like grains of salt) on body and fins',
      'Fish scratching against rocks and substrate',
      'Rapid breathing and gill irritation',
      'Clamped fins, hiding, loss of appetite',
    ],
    causes: [
      'Cryptocaryon irritans parasite introduction',
      'New fish added without quarantine',
      'Stress from poor water quality or aggression',
      'Temperature fluctuations weakening immune system',
    ],
    solutions: [
      'Move affected fish to a quarantine tank immediately',
      'Treat with copper-based medication (therapeutic level 2.0 ppm)',
      'Run a UV sterilizer on the display tank to kill free-swimming stage',
      'Soak food in garlic extract to boost immune response',
      'Maintain QT treatment for full 30-day lifecycle of the parasite',
      'Keep display tank fallow (fish-free) for 76 days to break the cycle',
      'Monitor copper levels daily with a test kit during treatment',
    ],
    prevention: [
      'Quarantine ALL new fish for at least 30 days before adding to display',
      'Use a prophylactic copper treatment in QT',
      'Avoid temperature swings — keep stable within 1°F',
      'Minimize stress: provide hiding spots, avoid overstocking',
    ],
    relatedParams: ['temperature', 'ammonia', 'nitrite'],
  },
  {
    id: 'nitrite-spike',
    name: 'Nitrite Spike',
    icon: 'emergency',
    category: 'water',
    urgency: 'critical',
    symptoms: [
      'Fish gasping at the surface or near flow outlets',
      'Brown-colored blood (methemoglobinemia)',
      'Lethargy and rapid gill movement',
      'Fish lying on the bottom, unresponsive',
    ],
    causes: [
      'Incomplete nitrogen cycle',
      'Die-off of beneficial bacteria (medication, power outage)',
      'Sudden bioload increase (too many fish added at once)',
      'Filter media replaced all at once',
    ],
    solutions: [
      'Perform an immediate 50% water change',
      'Add beneficial bacteria supplement (Fritz TurboStart, Microbacter7)',
      'Stop feeding for 24-48 hours to reduce bioload',
      'Dose Seachem Prime to detoxify nitrite temporarily',
      'Increase aeration and surface agitation',
      'Test nitrite every 6 hours and do water changes if above 0.5 ppm',
    ],
    prevention: [
      'Never replace all filter media at once — stagger replacements',
      'Add fish slowly, one or two at a time with weeks between additions',
      'Keep backup bacteria cultures on hand',
      'Monitor nitrite during cycling and after any disruption',
    ],
    relatedParams: ['nitrite', 'ammonia', 'nitrate', 'pH'],
  },

  // ── High ──────────────────────────────────────────────────
  {
    id: 'cyano-red-slime',
    name: 'Cyano / Red Slime',
    icon: 'water_damage',
    category: 'algae',
    urgency: 'high',
    symptoms: [
      'Red, burgundy, or dark purple slimy film on rocks and sand',
      'Film peels off in sheets when disturbed',
      'Bubbles forming under the slime mat',
      'Musty or earthy smell from the tank',
    ],
    causes: [
      'Excess nutrients (phosphates, dissolved organics)',
      'Low flow / dead spots in the tank',
      'Excessive blue-spectrum light or old bulbs',
      'Overfeeding and poor nutrient export',
    ],
    solutions: [
      'Reduce photoperiod and blue-spectrum intensity',
      'Increase water flow — reposition powerheads to eliminate dead spots',
      'Siphon cyano manually during water changes',
      'Test and reduce phosphates (target < 0.03 ppm)',
      'Dose Chemiclean (follow directions exactly, increase aeration)',
      'Increase protein skimmer efficiency',
      'Run GFO or RowaPhos to bind phosphates',
    ],
    prevention: [
      'Maintain strong, varied flow throughout the tank',
      'Feed conservatively and remove uneaten food',
      'Replace light bulbs on schedule (T5 every 9-12 months)',
      'Keep up with regular water changes',
    ],
    relatedParams: ['phosphate', 'nitrate'],
  },
  {
    id: 'dinoflagellates',
    name: 'Dinoflagellates',
    icon: 'bug_report',
    category: 'algae',
    urgency: 'high',
    symptoms: [
      'Brown or golden snot-like film on sand and rocks',
      'Bubbles forming on the surface of the film',
      'Film returns within hours after removal',
      'Stringy, mucus-like appearance (different from diatoms)',
    ],
    causes: [
      'Ultra-low nutrient levels (too clean of a tank)',
      'Low biodiversity in the microfauna',
      'Recent use of aggressive nutrient removal (carbon dosing, GFO)',
      'Disruption of the bacterial ecosystem',
    ],
    solutions: [
      'Raise nitrates to 5-10 ppm by reducing nutrient export or dosing NaNO3',
      'Run a UV sterilizer 24/7 to kill free-floating dinos',
      'Reduce photoperiod to 6 hours or do a 3-day blackout',
      'Add bacterial diversity products (Microbacter7, PodClean)',
      'Stop running GFO and reduce skimming',
      'Add a refugium with chaetomorpha to outcompete dinos',
      'Siphon dinos out during lights-on when they detach from substrate',
    ],
    prevention: [
      'Never chase zero nutrients — maintain NO3 at 5+ ppm',
      'Feed a diverse diet to maintain microfauna',
      'Avoid over-sterilizing the system',
      'Maintain a healthy refugium with live pods and macro algae',
    ],
    relatedParams: ['nitrate', 'phosphate'],
  },
  {
    id: 'alkalinity-crash',
    name: 'Alkalinity Crash',
    icon: 'trending_down',
    category: 'water',
    urgency: 'high',
    symptoms: [
      'Coral tissue recession (STN / RTN), especially on SPS',
      'Sudden loss of color in Acropora and Montipora',
      'White skeleton visible at base or tips of SPS corals',
      'Soft corals and LPS may shrink or retract',
    ],
    causes: [
      'Dosing pump failure or empty dosing container',
      'Calcium reactor CO2 ran out or malfunction',
      'Rapid coral growth consuming more Alk than expected',
      'Missed water changes in a heavily stocked tank',
    ],
    solutions: [
      'Test alkalinity immediately — identify how far it has dropped',
      'Raise Alk slowly: maximum 1 dKH per day to avoid shocking corals',
      'Check and recalibrate dosing pump or calcium reactor',
      'Verify dosing container levels and refill if empty',
      'Do a partial water change with fresh salt mix (matches target Alk)',
      'Monitor affected corals closely for 2 weeks for further recession',
    ],
    prevention: [
      'Set up alerts/alarms on dosing pumps for low levels',
      'Test alkalinity at least 2x per week',
      'Gradually increase dosing as coral colony grows',
      'Keep backup dosing solution mixed and ready',
    ],
    relatedParams: ['alkalinity', 'calcium', 'magnesium', 'pH'],
  },
  {
    id: 'temperature-spike',
    name: 'Temperature Spike',
    icon: 'device_thermostat',
    category: 'equipment',
    urgency: 'high',
    symptoms: [
      'Coral stress — tissue retraction, mucus production',
      'Fish hiding, heavy breathing, erratic swimming',
      'Visible mucus or slime on corals and rocks',
      'Temperature reading above 82°F / 28°C',
    ],
    causes: [
      'Heater malfunction (stuck on)',
      'Chiller failure during summer',
      'Power outage causing loss of cooling',
      'Extreme ambient room temperature',
    ],
    solutions: [
      'Float sealed bags of ice (zip-lock) in the sump — do NOT add ice directly',
      'Point a fan across the water surface to increase evaporative cooling',
      'Turn off or dim aquarium lights to reduce heat output',
      'Increase surface agitation for gas exchange and cooling',
      'Unplug the heater if it is malfunctioning',
      'Lower temperature gradually — max 2°F per hour to avoid shock',
      'If chiller is broken, set up a temporary DIY fan cooling rig',
    ],
    prevention: [
      'Use a temperature controller (e.g., InkBird) with heater AND fan/chiller',
      'Set high-temperature alert on your aquarium controller',
      'Keep a backup heater and fan available',
      'Use a UPS for critical equipment during power outages',
    ],
    relatedParams: ['temperature'],
  },

  // ── Medium ────────────────────────────────────────────────
  {
    id: 'hair-algae',
    name: 'Hair Algae',
    icon: 'grass',
    category: 'algae',
    urgency: 'medium',
    symptoms: [
      'Green filamentous algae growing on rocks and substrate',
      'Algae strands waving in the flow',
      'Coats coral plugs, frag racks, and equipment',
      'Difficult to remove — regrows quickly',
    ],
    causes: [
      'Elevated phosphates and/or nitrates',
      'Overfeeding',
      'Too much light or old light bulbs with shifted spectrum',
      'Insufficient clean-up crew (CUC)',
    ],
    solutions: [
      'Reduce feeding to once per day, small portions',
      'Manually remove as much algae as possible with a toothbrush',
      'Add clean-up crew: turbo snails, tuxedo urchins, emerald crabs',
      'Test phosphates and run GFO if above 0.05 ppm',
      'Reduce photoperiod to 8 hours',
      'Increase water changes to 15-20% weekly',
      'Consider a fluconazole treatment as a last resort',
    ],
    prevention: [
      'Maintain phosphates below 0.03 ppm',
      'Feed conservatively and use a feeding ring',
      'Keep a healthy population of algae grazers',
      'Perform consistent weekly water changes',
    ],
    relatedParams: ['phosphate', 'nitrate'],
  },
  {
    id: 'brown-diatoms',
    name: 'Brown Diatoms',
    icon: 'blur_on',
    category: 'algae',
    urgency: 'medium',
    symptoms: [
      'Brown dusty film on glass, rocks, and sand',
      'Easily wiped off but returns quickly',
      'Most common in new tanks (first 1-3 months)',
      'Appears on surfaces with the most light exposure',
    ],
    causes: [
      'Silicates leaching from new sand or rock',
      'New tank still establishing biological balance',
      'Using tap water or low-quality RO water with silicates',
      'Low-flow areas accumulating organic waste',
    ],
    solutions: [
      'Be patient — diatoms typically resolve on their own in 4-8 weeks',
      'Add clean-up crew: Trochus and Nassarius snails, conchs',
      'Wipe glass regularly with a magnetic cleaner',
      'Use high-quality RODI water (check TDS reads 0)',
      'Reduce silicates with a silicate-removing resin if persistent',
      'Increase flow to prevent settling',
    ],
    prevention: [
      'Always use 0 TDS RODI water for mixing and top-off',
      'Rinse new sand thoroughly before adding to the tank',
      'Maintain a proper CUC population from the start',
      'Be patient with new tank ugly phase — it passes',
    ],
    relatedParams: ['silicate', 'nitrate', 'phosphate'],
  },
  {
    id: 'aiptasia',
    name: 'Aiptasia',
    icon: 'pest_control',
    category: 'coral',
    urgency: 'medium',
    symptoms: [
      'Small clear or brown anemones appearing on rocks',
      'Spreading rapidly via pedal laceration',
      'Stinging nearby corals causing tissue damage',
      'Often found in shaded areas and crevices',
    ],
    causes: [
      'Introduced on live rock, coral frags, or frag plugs',
      'Excess nutrients fueling rapid reproduction',
      'Lack of natural predators in the tank',
    ],
    solutions: [
      'Inject with Aiptasia-X or lemon juice directly into the oral disc',
      'Add peppermint shrimp (Lysmata wurdemanni) — they eat small aiptasia',
      'Introduce a Copperband Butterflyfish or Matted Filefish',
      'Use a laser pointer (high-powered blue) to burn individual polyps',
      'Do NOT touch or tear them — fragments regenerate into new aiptasia',
      'Treat aggressively before they spread to unreachable areas',
    ],
    prevention: [
      'Dip all new corals and frag plugs in coral dip before adding',
      'Inspect new live rock carefully in a bucket before adding',
      'Keep nutrient levels in check to slow their growth',
      'Maintain a peppermint shrimp as ongoing biological control',
    ],
    relatedParams: ['nitrate', 'phosphate'],
  },
  {
    id: 'low-ph',
    name: 'Low pH',
    icon: 'speed',
    category: 'water',
    urgency: 'medium',
    symptoms: [
      'pH consistently below 7.8',
      'Slow coral growth despite good alkalinity',
      'Fish showing signs of stress or heavy breathing',
      'Coralline algae growth stalling',
    ],
    causes: [
      'Poor ventilation — high CO2 in the room',
      'Overstocked tank with high bio-load',
      'Low alkalinity not buffering pH properly',
      'Sealed house with poor air exchange (winter months)',
    ],
    solutions: [
      'Increase room ventilation — open a window or run exhaust fan',
      'Use Kalkwasser (calcium hydroxide) in your ATO system',
      'Add a CO2 scrubber on the protein skimmer air intake',
      'Run a refugium with chaetomorpha on a reverse light schedule',
      'Check and correct alkalinity first (target 8-9 dKH)',
      'Move skimmer air intake to draw from outside the house/stand',
    ],
    prevention: [
      'Ensure the fish room has adequate ventilation',
      'Use Kalkwasser in ATO as part of the regular routine',
      'Monitor pH continuously with a probe and controller',
      'Run a refugium on a reverse photoperiod',
    ],
    relatedParams: ['pH', 'alkalinity', 'calcium'],
  },
  {
    id: 'phosphate-issues',
    name: 'Phosphate Issues',
    icon: 'science',
    category: 'water',
    urgency: 'medium',
    symptoms: [
      'Nuisance algae growth (hair, turf, film algae)',
      'Coral color loss — browning or darkening',
      'Slowed coral growth despite good calcium and alkalinity',
      'Persistent cyano or dinoflagellate blooms',
    ],
    causes: [
      'Overfeeding — uneaten food decomposing',
      'Insufficient protein skimming or filtration',
      'Tap water containing phosphates',
      'Decay of detritus in rocks and sand bed',
    ],
    solutions: [
      'Run GFO (granular ferric oxide) in a media reactor',
      'Use RowaPhos or PhosGuard in a filter bag',
      'Reduce feeding — target what fish consume in 1-2 minutes',
      'Increase water changes with 0 TDS RODI water',
      'Turkey-baste rocks and substrate to suspend detritus for skimmer to catch',
      'Clean filter socks every 2-3 days',
    ],
    prevention: [
      'Feed conservatively and use quality frozen food (rinse before adding)',
      'Use only RODI water for mixing and top-off',
      'Run GFO passively in a filter bag at all times',
      'Clean mechanical filtration regularly',
    ],
    relatedParams: ['phosphate', 'nitrate'],
  },

  // ── Low ───────────────────────────────────────────────────
  {
    id: 'coralline-not-growing',
    name: 'Coralline Algae Not Growing',
    icon: 'spa',
    category: 'coral',
    urgency: 'low',
    symptoms: [
      'No purple, pink, or red coralline growth after several months',
      'Rock surfaces remain dull and lifeless',
      'New equipment and glass stay clean (no pink film)',
    ],
    causes: [
      'Calcium below 400 ppm',
      'Alkalinity below 7 dKH',
      'Magnesium below 1300 ppm',
      'Elevated phosphates inhibiting coralline settlement',
      'No coralline seed / inoculation in the system',
    ],
    solutions: [
      'Ensure calcium is at 420+ ppm, alkalinity 8+ dKH, magnesium 1350+ ppm',
      'Scrape existing coralline from a friend\'s tank or old plug to seed your system',
      'Reduce phosphates below 0.03 ppm',
      'Maintain stable parameters — coralline hates swings',
      'Be patient — coralline can take 3-6 months to establish',
      'Try a coralline booster product (e.g., ARC Reef\'s Coralline in a Bottle)',
    ],
    prevention: [
      'Keep Ca, Alk, and Mg at stable target levels',
      'Maintain low phosphates',
      'Avoid scraping coralline from back glass — leave it as a seed source',
      'Ensure moderate lighting — coralline prefers blue-spectrum light',
    ],
    relatedParams: ['calcium', 'alkalinity', 'magnesium', 'phosphate'],
  },
  {
    id: 'vermetid-snails',
    name: 'Vermetid Snails',
    icon: 'local_fire_department',
    category: 'coral',
    urgency: 'low',
    symptoms: [
      'Small tubes (2-5mm) protruding from rocks or coral bases',
      'Mucus webs / nets cast out to trap food',
      'Mucus webs irritating nearby coral tissue',
      'Increasing in number over time',
    ],
    causes: [
      'Introduced on live rock or coral frags',
      'Excess nutrients providing abundant food',
      'No natural predators in the system',
    ],
    solutions: [
      'Manually break tubes with bone cutters or pliers at the base',
      'Superglue over the tube opening to seal them in',
      'Add a melanurus wrasse or yellow coris wrasse — they eat small vermetids',
      'Reduce feeding to limit food available for their mucus nets',
      'Be persistent — manual removal over time reduces population',
    ],
    prevention: [
      'Inspect coral frags and plugs closely before adding',
      'Dip new corals in Bayer or CoralRx',
      'Maintain a wrasse species that preys on small tube worms',
      'Keep nutrient levels moderate to limit their food supply',
    ],
    relatedParams: ['nitrate', 'phosphate'],
  },
  {
    id: 'bristle-worms',
    name: 'Bristle Worms',
    icon: 'bug_report',
    category: 'fish',
    urgency: 'low',
    symptoms: [
      'Pink, red, or orange segmented worms seen at night',
      'Worms retreating into rocks when light is turned on',
      'Bristle-like setae visible along their body',
      'Found scavenging on uneaten food or detritus',
    ],
    causes: [
      'Naturally introduced on live rock',
      'Population grows with excess food / detritus',
      'Normal part of a healthy reef ecosystem',
    ],
    solutions: [
      'Most bristle worms are beneficial detrivores — no action needed',
      'Only remove if you identify a fireworm (thicker, more colorful, painful sting)',
      'Trap with a commercial worm trap or DIY bottle trap baited with shrimp at night',
      'Add an arrow crab or coral banded shrimp — they eat small worms',
      'Reduce feeding to limit population growth if they are excessive',
      'Handle with gloves — bristles can embed in skin and cause irritation',
    ],
    prevention: [
      'Inspect live rock at night before adding to the display',
      'Feed conservatively to prevent population explosions',
      'Accept them as part of a healthy ecosystem — they clean up waste',
      'Only intervene if fireworms are confirmed',
    ],
  },
];

export function getProblemsByCategory(cat: string): Problem[] {
  if (cat === 'all') return PROBLEMS;
  return PROBLEMS.filter((p) => p.category === cat);
}
